// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see
// https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/custom_action/custom_action.proto)

#include <iomanip>

#include "custom_action_impl.h"
#include "plugins/custom_action/custom_action.h"

namespace mavsdk {

using ActionToExecute = CustomAction::ActionToExecute;

CustomAction::CustomAction(System& system) : PluginBase(), _impl{new CustomActionImpl(system)} {}

CustomAction::CustomAction(std::shared_ptr<System> system) :
    PluginBase(),
    _impl{new CustomActionImpl(system)}
{}

CustomAction::~CustomAction() {}

void CustomAction::set_custom_action_async(ActionToExecute action, const ResultCallback callback)
{
    _impl->set_custom_action_async(action, callback);
}

CustomAction::Result CustomAction::set_custom_action(ActionToExecute action) const
{
    return _impl->set_custom_action(action);
}

void CustomAction::subscribe_custom_action(CustomActionCallback callback)
{
    _impl->custom_action_async(callback);
}

CustomAction::ActionToExecute CustomAction::custom_action() const
{
    return _impl->custom_action();
}

void CustomAction::respond_custom_action_async(
    ActionToExecute action, Result result, const ResultCallback callback)
{
    _impl->respond_custom_action_async(action, result, callback);
}

CustomAction::Result
CustomAction::respond_custom_action(ActionToExecute action, Result result) const
{
    return _impl->respond_custom_action(action, result);
}

bool operator==(const CustomAction::ActionToExecute& lhs, const CustomAction::ActionToExecute& rhs)
{
    return (rhs.id == lhs.id) && (rhs.timeout == lhs.timeout) && (rhs.progress == lhs.progress);
}

std::ostream& operator<<(std::ostream& str, CustomAction::ActionToExecute const& action_to_execute)
{
    str << std::setprecision(15);
    str << "action_to_execute:" << '\n' << "{\n";
    str << "    id: " << action_to_execute.id << '\n';
    str << "    timeout: " << action_to_execute.timeout << '\n';
    str << "    progress: " << action_to_execute.progress << '\n';
    str << '}';
    return str;
}

std::ostream& operator<<(std::ostream& str, CustomAction::Result const& result)
{
    switch (result) {
        case CustomAction::Result::Unknown:
            return str << "Unknown";
        case CustomAction::Result::Success:
            return str << "Success";
        case CustomAction::Result::Error:
            return str << "Error";
        case CustomAction::Result::Timeout:
            return str << "Timeout";
        case CustomAction::Result::Unsupported:
            return str << "Unsupported";
        case CustomAction::Result::InProgress:
            return str << "In Progress";
        default:
            return str << "Unknown";
    }
}

} // namespace mavsdk
